<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="OpenTelemetry.Exporter.OpenTelemetryProtocol" Version="1.18.0" />
    <PackageReference Include="OpenTelemetry.Extensions.Hosting" Version="1.18.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../Intake.Compliance.Application/Intake.Compliance.Application.csproj" />
    <ProjectReference Include="../Intake.Compliance.Infrastructure/Intake.Compliance.Infrastructure.csproj" />
  </ItemGroup>

</Project>
